esphome:
  name: s3-mini
  friendly_name: s3-mini
  platformio_options:
    platform: https://github.com/platformio/platform-espressif32.git
    board: lolin_s3_mini
    framework: arduino
    board_build.flash_mode: dio

esp32:
  variant: esp32s3
  board: lolin_s3_mini
  framework: 
    type: arduino
    version: latest

logger:
  level: DEBUG

api:
  encryption:
    key: !secret api_key

ota:
  - platform: esphome
    password: !secret ota_password

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  ap:
    ssid: "S3-Mini Fallback Hotspot"
    password: !secret ap_password

captive_portal:

esp32_ble_tracker:

ble_client:
  - mac_address: XX:XX:XX:XX:XX:XX
    id: veepeak

external_components:
  - source: my_components

obd2_ble:
  id: mycar
  service_uuid: "0xFFF0"
  characteristic_uuid:
    write: "0xFFF2"
    notify: "0xFFF1"
  #init_commands: "ATD ATE0 ATL0 ATH0 ATS0 ATSP0 ATDPN 0100 0120 0140 0160 0180 01A0 01C0 050100 0600 0900"
  #command_delay: 1000
  #command_wait: 5000

sensor:
  - platform: obd2_ble
    obd2_ble_id: mycar
    name: "Engine RPM"
    can_id: "7E8"
    mode: "01"
    pid: "0C"
    unit_of_measurement: "rpm"
  - platform: obd2_ble
    obd2_ble_id: mycar
    name: "Vehicle Speed"
    can_id: "7E8"
    mode: "01"
    pid: "0D"
    unit_of_measurement: "km/h"

text_sensor:
  - platform: obd2_ble
    obd2_ble_id: mycar
    name: "Stored DTC"
    can_id: "7E8"
    mode: "03"
  - platform: obd2_ble
    obd2_ble_id: mycar
    name: "Pending DTC"
    can_id: "7E8"
    mode: "07"
  - platform: obd2_ble
    obd2_ble_id: mycar
    name: "Vehicle VIN"
    can_id: "7E8"
    mode: "09"
    pid: "02"
  - platform: obd2_ble
    obd2_ble_id: mycar
    name: "Permanent DTC"
    can_id: "7E8"
    mode: "0A"

binary_sensor:
  - platform: obd2_ble
    obd2_ble_id: mycar
    name: "Stored P0010"
    mode: "03"
    code: "P0010"
  - platform: obd2_ble
    obd2_ble_id: mycar
    name: "Stored P0011"
    mode: "03"
    code: "P0011"

